/*
https://programmers.co.kr/learn/courses/30/lessons/59041

SELECT NAME, COUNT(*) FROM ANIMAL_INS GROUP BY NAME  HAVING COUNT(*) > 1;
null인 경우를 신경 쓰지 않아서 실패함..

SELECT NAME, COUNT(*) FROM ANIMAL_INS WHERE NAME IS NOT NULL GROUP BY NAME  HAVING COUNT(NAME) > 1;

*/

SELECT NAME, COUNT(NAME) FROM ANIMAL_INS GROUP BY NAME  HAVING COUNT(NAME) > 1;